services:
  backend:
    build: ./backend
    volumes:
      - ./media:/media:ro
      - ./backend:/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "8000:8000"
  media:
    build: ./media
    ports:
      - "9000:9000"
